### ISSUE TITLE
Events are not triggered

### ISSUE THREAD

**Issue by sathish-a** [masenf/reflex-intersection-observer#3]
Hey, I'm currently tackling a project that involves fetching images as users scroll down. This repository is exactly what I was looking for, so thanks for sharing it. I've taken some components in my project and wrapped them inside an `rx.cond` block to ensure I handle different scenarios properly. However, I've noticed that neither the `on_intersect` nor the `on_non_intersect` functions are being triggered when I wrap them inside the `rx.cond` block. It's a bit perplexing because everything seems fine when I work on isolated parts of the project. Could you help me figure out if this is the right approach or if there's something I might be overlooking?

To reproduce:

```python
import reflex as rx

from reflex_intersection_observer import intersection_observer


BATCH_SIZE = 15


class State(rx.State):
    items: list[str] = [f"Item {ix}" for ix in range(BATCH_SIZE)]

    def handle_intersect(self, entry):
        print(f"Intersected! {entry} Load more items.")
        self.items.extend(
            [
                f"Item {ix}"
                for ix in range(len(self.items), len(self.items) + BATCH_SIZE)
            ]
        )

    def handle_non_intersect(self, entry):
        print(f"Non-intersected! {entry}")


def index() -> rx.Component:
    scroll_view = rx.center(
        rx.scroll_area(
            rx.vstack(
                rx.foreach(State.items, rx.text),
                intersection_observer(
                    "Infinite Scroll Target",
                    root="#scroller",
                    root_margin="0px",
                    threshold=0.9,
                    on_intersect=State.handle_intersect,
                    on_non_intersect=State.handle_non_intersect,
                    # The target object doesn't need to be visible.
                    # visibility="hidden"
                ),
                justify="start",
                spacing="3",
                font_size="2em",
            ),
            type="hover",
            id="scroller",
            border="1px solid black",
            width="85vw",
            height="75vh",
        ),
        padding_top="5em",
    )
    
    # simple condition check.
    return rx.cond(
        State.is_hydrated,
        scroll_view,
        rx.chakra.spinner(color="purple", size="xl"),
    )



app = rx.App()
app.add_page(index)

```

**Comment by masenf** [comment]
Thanks for reporting.

The issue seems to be that the plugin is attempting to register the `IntersectionObserver` on the `#scroller` element when the page initially loads, but because the `#scroller` is behind the `rx.cond`, it doesn't actually exist when the page first loads, so the observer cannot register against it.

If i hack the code to add `[state.is_hydrated]` to the `useEffect` dependency array where the observer is being registered, then it does actually start to work, but that's not a generalizable solution that would work for any potential condition, especially not more complex compound conditions ones involving multiple vars.

**Comment by masenf** [comment]
@sathish-a thanks for using this component.

I implemented a kind of workaround for your particular situation that you can try via

```console
pip install git+https://github.com/masenf/reflex-intersection-observer@enable-later
```

Unfortunately it's not a complete solution to this problem because if the `rx.cond` allows the target element to be removed and re-added to the DOM later, that action won't re-register the observer so the on_intersect functionality will break.

But if the condition just happens once on initial page load, then the proposed solution should work around it.

I can merge it in later this week as a stop-gap if it's working for you.

**Comment by sathish-a** [comment]
@masenf, I just wanted to drop a quick note of appreciation for your swift response—it really means a lot. Your suggested patch above worked like a charm and neatly resolved my issue. I've seamlessly integrated it into my project, and everything is now running smoothly. Thanks again!
